---
- name: Установка gitea из бинарника
  hosts: server
  become: true
  tasks:
    - name: Установка файла с переменными
      ansible.builtin.include_vars:
        vars.yml
    - name: Создание директорий
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ gitea.gitea_user }}"
        group: "{{ gitea.gitea_group }}"
        mode: '0755'
      loop:
        - "{{ gitea.gitea_home }}"
        - "{{ gitea.gitea_repo_path }}"
        - "/etc/gitea"
    - name: Скачивание бинарника
      ansible.builtin.get_url:
        url: "{{ gitea.gitea_download_url }}"
        dest: "{{ gitea.gitea_bin_path }}"
        mode: '0755'
    - name: Создание конфига
      ansible.builtin.copy:
        dest: "{{ gitea.gitea_config_path }}"
        content: |
          APP_NAME = Gitea
          RUN_MODE = prod
          [server]
          DOMAIN = localhost
          ROOT_URL = http://localhost:3000/
          DISABLE_SSH = true
          HTTP_PORT = 3000
          LFS_START_SERVER = true
          PATH = /var/lib/gitea/lfs
          LFS_JWT_SECRET = random_lfs_jwt_secret
          OFFLINE_MODE = false
          START_SSH_SERVER = false
          DISABLE_TLS = true

          [database]
          DB_TYPE = sqlite3
          PATH = /var/lib/gitea/gitea.db

          [repository]
          APP_DATA_PATH = {{ gitea.gitea_repo_path }}

          [security]
          INSTALL_LOCK = true
          SECRET_KEY = random_secret_key
        owner: "{{ gitea.gitea_user }}"
        group: "{{ gitea.gitea_group }}"
        mode: '0644'
    - name: Создание сервисного файла
      ansible.builtin.copy:
        dest: /etc/systemd/system/gitea.service
        content: |
          [Unit]
          Description=Gitea
          After=network.target

          [Service]
          User={{ gitea.gitea_user }}
          Group={{ gitea.gitea_group }}
          ExecStart={{ gitea.gitea_bin_path }} web
          WorkingDirectory={{ gitea.gitea_home }}
          Restart=always
          Environment=USER={{ gitea.gitea_user}} HOME={{ gitea.gitea_home }} GITEA_WORK_DIR={{ gitea.gitea_home }}
          [Install]
          WantedBy=multi-user.target
        mode: '0644'
    - name: Запуск gitea
      ansible.builtin.systemd:
        daemon_reload: true
        name: gitea
        enabled: true
        state: started
